#!/bin/sh

case $BLOCK_BUTTON in
	4) xbacklight -inc 4 ;;
	5) xbacklight -dec 4 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo "💡;" "$(xbacklight -get)" "%" | sed 's/ //g; s/;/ /g'
