#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd,%mem --sort=%mem | awk '{a[$1]+=$2}END{for(i in a) print i,a[i] "%"}' | sort -n -r -k2 | head | column -t
)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

mpstat 2 1 | awk 'END{printf "%.1f%%\n", (100-$NF)}'
